<?php
    
?>   
    
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Social Mint</title>
  </head>
  <body>
<div class="container">

    <p class="mt-2" style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font: size 25px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style="font-size:25px;line-height:107%;">Social Mint Privacy Policy</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">In this Marketplace Privacy Policy, Social Mints LLC. and our affiliates (collectively, &ldquo;<strong>Social Mints</strong>&rdquo; or &ldquo;<strong>We</strong>&rdquo;), provide information about how we use, collect and transfer personally identifiable data from visitors to&nbsp;our Marketplaces (collectively the &quot;<strong>Marketplace</strong>&quot;) and users of our services.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">1. Scope</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">This Privacy Policy covers only data collected through the Marketplace and not any other data collection or processing, including, without limitation, data collection practices of other Marketplaces to which we link or data that we or our subsidiaries or affiliates collect offline or through Marketplaces, products, or services that do not display a direct link to this Privacy Policy.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">2. Collection, Use, and Sharing of Data</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">2.1 Browser and device information</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Social Mints collects information from visitors of the Marketplace, including the domain names, IP and MAC addresses, browser types, and unique device identifiers of such visitors. This information includes the number of visits, average time spent on the Marketplace, pages viewed and similar information. This information may also include usage information about the page-by-page paths you take as you browse through the Marketplace. Social Mints uses this information to measure the use of the Marketplace and to develop ideas to improve the content of the Marketplace. For more information regarding Social Mints use of this information, please see the sections on &ldquo;Cookies and Other Tracking Technologies&rdquo; and &ldquo;Analytics&rdquo; below. We may combine such information with information provided by you.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">2.2 Personal information provided by you</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">There are times, however, when we may need additional information from you, including personal information that may be used to identify you. This information includes items such as your name, address, telephone number, and email address. The information we collect is typically used by us to respond to your inquiry, process an order or allow you to access specific account/profile information.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">2.3 Information from third parties</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may receive information about you from third parties such as social networks (subject to the user&apos;s privacy settings and the privacy policy of the social network), service providers which allow us to verify, enhance or supplement your information, and business partners to whom we are offering a service. We are not responsible for third-party use of information.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">2.4 How do we use your information?</span></strong></p>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><span style='font-family:"Calibri",sans-serif;color:black;'>We use your personal information for the following purposes:</span></p>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Service Delivery</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>, including to:</span></p>
    <ul style="list-style-type: disc;margin-left:0in;">
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Provide, operate, maintain, and secure the Service;</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Create, maintain, and authenticate your account; and&nbsp;</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Process transactions.</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></li>
    </ul>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Communicating with You</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>, including to:&nbsp;</span></p>
    <ul style="list-style-type: disc;margin-left:0in;">
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>send you updates about administrative matters such as changes to our terms or policies; and</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>provide user support, and respond to your requests, questions and feedback.</span></li>
    </ul>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></strong></p>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Service Improvement</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>, including to:&nbsp;</span></p>
    <ul style="list-style-type: disc;margin-left:0in;">
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>improve the Service and create new features;&nbsp;</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>personalize your experience; and&nbsp;</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>create and derive insights from de-identified and aggregated information.&nbsp;</span></li>
    </ul>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></strong></p>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Marketing and Advertising</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>, including for:</span></p>
    <div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
        <ul style="margin-bottom:0in;list-style-type: disc;margin-left:0in;">
            <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Direct Marketing:</span></strong><span style="color:black;">&nbsp;To send you marketing communications, including notifying you of special promotions, offers and events via email and other means; and</span></li>
        </ul>
    </div>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Compliance and Protection,&nbsp;</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>including to:</span></p>
    <ul style="list-style-type: disc;margin-left:0in;">
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Comply with applicable laws, lawful requests, and legal process, such as to respond to subpoenas or requests from government authorities;</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Protect our, your or others&rsquo; rights, privacy, safety or property (including by making and defending legal claims);</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Audit our compliance with legal and contractual requirements and internal policies; and</span></li>
        <li><span style='font-family:"Calibri",sans-serif;color:black;'>Prevent, identify, investigate and deter fraudulent, harmful, unauthorized, unethical or illegal activity, including cyberattacks and identity theft.</span></li>
    </ul>
    <h3 style='margin-top:2.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></strong></h3>
    <h3 style='margin-top:2.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:107%;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F3763;font-weight:normal;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>3. Personal Information Sharing</span></strong></h3>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></strong></p>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>3.1 Our Sharing:</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;We may share personal information with:</span></p>
    <ul style="list-style-type: disc;margin-left:0in;">
        <li><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Service Providers</span></strong><span style="color:black;">, including hosting services, email services, advertising and marketing services, payment processors, customer support services, and analytics services.</span></li>
        <li><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Professional Advisors</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>, such as lawyers and accountants, where doing so is necessary to facilitate the services they render to us.&nbsp;</span></li>
        <li><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Business Transaction Recipients,&nbsp;</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>such as counterparties and others assisting with a merger, acquisition, financing, reorganization, bankruptcy, receivership, dissolution, asset sale, or similar transaction, and with successors or affiliates as part of or following that transaction.</span></li>
        <li><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Government Authorities</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>, where required to do so for the Compliance and Protection purposes described above.</span></li>
        <li><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Affiliates:&nbsp;</span></strong><span style="color:black;">We may share personal information with our current and future affiliates, meaning an entity that controls, is controlled by, or is under common control with Foundation. Our affiliates may use the personal information we share in a manner consistent with this Privacy Policy.</span></li>
        <li><strong><span style='font-family:"Calibri",sans-serif;color:black;'>Complainants:&nbsp;</span></strong><span style="color:black;">If you are a Creator(s), Artist(s) and or Collector(s), we may, at our sole discretion, share your personal information with individuals who claim that your Digital Artwork or Art Content may infringe their intellectual property and other proprietary rights.</span></li>
    </ul>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;</span></strong></p>
    <p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman",serif;margin-top:0in;background:white;'><strong><span style='font-family:"Calibri",sans-serif;color:black;'>3.2 Your Sharing:</span></strong><span style='font-family:"Calibri",sans-serif;color:black;'>&nbsp;Your transactions through the Service will be recorded on the blockchain and associated with your wallet ID.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">3.3&nbsp;</span></strong><span style="font-size:16px;line-height:107%;">If you choose to share any personal information with us, we will use it in accordance with this Privacy Policy and applicable law. We may use your personal information to: improve the Marketplace or Social Mints products and services; customize your experience with the Marketplace, or to serve you specific content that is relevant to you; contact you regarding your use of the Marketplace and, in our discretion, changes to our policies; provide you with Marketplace-related notices; send you advertisements and marketing for Social Mints products and services in accordance with the law; to notify you about changes to our Marketplaces and services; send you service notices; deal with enquiries and complaints; comply with any legal or regulatory requirements and otherwise to any respond to any relevant regulator or competent authority as required by law; understand user trends and patterns; for business administration; and for purposes disclosed elsewhere in this Privacy Policy, at the time you provide your personal information, or with your consent. We may also use information for any internal purpose, such as quality control efforts or customer analysis.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">&nbsp;3.4 Retention of information</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may store your information for as long as it is required for our business purposes, including the period after which any customer relationship has ceased.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">3.5 Sharing of information</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We will only share your information with third parties in accordance with applicable law.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may share with third-parties information that is not associated with your name or identity, such as Marketplace usage information, non-personally identifiable demographic information, and aggregate user statistics in accordance with applicable law.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may share your personal information with non-affiliated third parties as necessary for us to provide the product or service you or your lender/service provider have requested of us, as permitted by law, with third party service providers so that they may perform certain services for us, or as otherwise specified herein. Such disclosures may include situations in which we are required to respond to subpoenas or other legal process or are responding to the request of governmental authorities conducting an investigation.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may also provide all of the types of non-public personal information listed above to one or more of our affiliated companies in connection with our services and other business purposes.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">It is possible that Social Mints, its subsidiaries, affiliates, joint venture companies, or any combination of them, could merge with or be acquired by another legal entity. In such event, or in the event of any other proposed or actual purchase, sale (including a liquidation, realization, foreclosure or repossession), lease, merger, amalgamation or any other type of acquisition, disposal, transfer, conveyance or financing of all or any portion of Social Mints or of any of the business or assets or shares of Social Mints or a subsidiary or division thereof, Social Mints may share your information with third parties.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Furthermore, and subject to your consent where required by law, we may also provide all the information we collect, as described above, to companies that perform marketing services on our behalf, on behalf of our affiliated companies or to other financial institutions with which we or our affiliated companies have joint marketing agreements. In some circumstances, we will request your consent to share your information with nonaffiliated third parties, such as lenders, realtors, and insurers, so that they may offer you products and services that may be of interest to you.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">4 Cookies and Other Tracking Technologies</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">The Marketplace uses &ldquo;cookie&rdquo; technology to measure Marketplace activity and to collect information such as browser type, time spent on the Marketplace, pages visited and other information about your visit to the Marketplace. Cookies are also used to prefill information previously entered forms and to customize information to your personal tastes. A cookie is an element of data that an Internet site can send to your browser. Cookies are stored on your computer. We may share information about you that we collect through a cookie with third-parties who help us analyze Marketplace data, in accordance with the law.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">4.1&nbsp;</span></strong><span style="font-size:16px;line-height:107%;">On our Marketplace we use the following types of cookies:</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">(a) Strictly necessary cookies</span></strong><span style="font-size:16px;line-height:107%;">&nbsp;- These cookies are essential to enable the user to navigate around the Marketplace securely and to provide the user with services they have specifically requested.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">(b) Functionality cookies</span></strong><span style="font-size:16px;line-height:107%;">&nbsp;- These cookies enhance the functionality of the Marketplace by storing user preferences. For instance, they can remember your name and location, if you provide this information and the types of content you are interested in.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">(c) Performance cookies</span></strong><span style="font-size:16px;line-height:107%;">&nbsp;- These cookies improve the performance of the Marketplace. For instance, they help pages load quicker.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">(d) Analytics cookies</span></strong><span style="font-size:16px;line-height:107%;">&nbsp;- We may use third party analytics services such as Google Analytics and others. Your IP address and other information will be collected by automated means to report on your use of the services.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">If you do not want information collected through the use of cookies, there is a simple procedure in most browsers that allows you to automatically decline cookies or be given the choice of declining or accepting the transfer to your computer of a particular cookie (or cookies) from a particular site. If, however, you do not accept our cookies, you may experience some inconvenience in your use of the Marketplace. &nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may also include small graphic images called web beacons, also known as &quot;Internet tags&quot; or &quot;clear gifs,&quot; in our web pages and email messages. We may use web beacons or similar technologies for a number of purposes, including, without limitation, to count the number of visitors to the Marketplace, to monitor how users navigate the Marketplace, and to count how many emails that we sent were actually opened or how many particular articles or links were actually viewed.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may also use embedded scripts on the Marketplace. An embedded script is programming code that is designed to collect information about your interactions with the Marketplace. It is temporarily downloaded onto your computer from our web server or a third party with whom we work, is active only while you are connected to the Marketplace, and is deleted or deactivated thereafter.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">5. Analytics</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We may use third party analytics service providers, including but not limited to Google Analytics, to evaluate and provide us with information about the use of the Marketplace. These third parties use cookies, web beacons, pixels, embedded scripts and other, similar technologies to automatically collect information about your Marketplace use, report Marketplace trends, and help us compile Marketplace metrics. &nbsp;You can learn about Google&rsquo;s specific practices by going to&nbsp;</span><a href="http://www.google.com/policies/privacy/partners/" target="_blank"><span style="font-size:16px;line-height:107%;color:#3899D5;">www.google.com/policies/privacy/&zwnj;partners/</span></a><span style="font-size:16px;line-height:107%;">.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We use Google Analytics Advertising Features with Google Signals, which includes Remarketing with Google Analytics, Google Display Network Impression Reporting, and Google Analytics Demographics and Interests Reporting to advertise online. Google Signals provides insight into cross-device user journeys and allows us to remarket to signed-in Google users across devices. Marketplaces and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone&rsquo;s past visits to a Marketplace.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">6. Opt-out</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">If you would like us to stop sending you marketing communications, you may use the opt-out link set out below or the unsubscribe link in our marketing communications. Although we encourage you to use the opt-out link because it is automated, you may also contact us.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">7.1 Opt-out Contacts</span></strong></p>
    <table style="border: none;width:649.5pt;background:white;border-collapse:collapse;">
        <tbody>
            <tr>
                <td style="width:211.5pt;padding:.75pt .75pt .75pt .75pt;">
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">Social Mint<span style="color:black;">s</span></span></strong></p>
                </td>
                <td style="width:429.0pt;padding:.75pt .75pt .75pt .75pt;"><br></td>
            </tr>
            <tr>
                <td style="width:211.5pt;padding:.75pt .75pt .75pt .75pt;">
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;color:black;">Email: optout@socialmint.net</span></strong><span style="font-size:16px;line-height:107%;color:black;">&nbsp;</span></p>
                </td>
                <td style="width:429.0pt;padding:.75pt .75pt .75pt .75pt;">
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">&nbsp;</span></p>
                </td>
            </tr>
            <tr>
                <td style="width:211.5pt;padding:.75pt .75pt .75pt .75pt;"><br></td>
                <td style="width:429.0pt;padding:.75pt .75pt .75pt .75pt;">
                    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">&nbsp;</span></p>
                </td>
            </tr>
        </tbody>
    </table>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;color:white;">If you, or another user of your device, wish to withdraw your cookies consent at any time, you have the ability to accept or decline cookies by modifying your browser setting. You may also go to&nbsp;</span><a href="http://www.allaboutcookies.org/" target="_blank"><span style="font-size:16px;line-height:107%;color:#3899D5;">www.allaboutcookies.org</span></a><span style="font-size:16px;line-height:107%;">&nbsp; for instructions on how to disable cookies. You may opt-out from Google Analytics&nbsp;</span><a href="https://tools.google.com/dlpage/gaoptout/" target="_blank"><span style="font-size:16px;line-height:107%;color:#3899D5;">here</span></a><span style="font-size:16px;line-height:107%;">&nbsp;or by downloading the Google Analytics opt-out browser add-on, available at:&nbsp;</span><a href="https://tools.google.com/dlpage/gaoptout" target="_blank"><span style="font-size:16px;line-height:107%;color:#3899D5;">https://tools.google.com/dlpage/gaoptout</span></a><span style="font-size:16px;line-height:107%;">. In some instances, when you opt-out, a new cookie (<strong>Opt-Out-Cookie</strong>) is placed in your web browser. This tells the third party provider to cease data collection from your browser and prevents advertisements from being delivered to you.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">8. Social Features</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Certain functionality on the Marketplace may permit interactions that you initiate between the Marketplace and a third party Marketplace or service (&ldquo;<strong>Social Features</strong>&rdquo;). If you choose to use Social Features, information you post or provide access to may be publicly displayed by the provider of the Social Feature that you use. Similarly, if you post information on a third party platform that references the Marketplace (e.g., by using a hashtag associated with Social Mints in a tweet or status update), your post may be published on the Marketplace in accordance with the terms of the third party Marketplace or service. Also, both Social Mints and the third party may have access to certain information about you and your use of the Marketplace and the third party site or service. The information we collect in connection with Social Features is subject to this Privacy Policy. The information collected and stored by the third party remains subject to the third party&rsquo;s privacy practices.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">9. California Privacy Rights</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">When California customers provide personal information to a business, they have the right to request certain disclosures if that business shares personal information with third parties for the third parties&apos; direct marketing purposes. Once per calendar year the customer may request that the business provide a list of companies with which it shares personal information for those companies&apos; direct marketing purposes, and a list of the categories of personal information that the business shares. Social Mints generally does not sell products or services directly to individual California consumers. However, if we engage in such contact, you may request information about our compliance with this law by contacting us.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Any such inquiry must include &quot;California Privacy Rights Request&quot; in the first line of the description and include your name, street address, city, state, and ZIP code. Please note that we are only required to respond to one request per customer each year, and we are not required to respond to requests made by means other than through this email address or mail address.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">For information regarding Social Mints obligations under the California Consumer Privacy Act (CCPA), please&nbsp;</span><a href="https://www.corelogic.com/landing-pages/california-consumer-privacy-act.aspx" target="_blank" title="CCPA"><span style="font-size:16px;line-height:107%;color:#3899D5;">click here</span></a><span style="font-size:16px;line-height:107%;">.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">10. Children&rsquo;s Online Privacy</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Our Site is not intended for children under the age of 13. All persons under the age of 13 must explicitly have their guardian and or parent&rsquo;s permission to enter the Marketplace. We do not intentionally or knowingly collect personally identifiable information from children under the age of 13 and we request that individuals under the age of 13 do not submit any personal information on the Marketplace. If we learn that we have received identifying information from a user under the age of 13, we will delete this information.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">11. Third Party Marketplaces</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">There may be hyperlinks on the Marketplace to other Marketplaces or locations that are operated and controlled by third parties (&quot;<strong>Third Party Marketplaces</strong>&quot;). These Third-Party Marketplaces may solicit personal information from you. We make no representations regarding the policies or business practices of such Third Party Marketplaces and encourage you to familiarize yourself with their privacy policies before providing them with your personal information.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">12. Investigative Consumer Reports (California Residents)</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Privacy Notice: Preparation and Processing of Investigative Consumer Reports</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">This notice is provided to California residents. Under California law, an &quot;investigative consumer report&quot; is a consumer report containing information on a consumer&apos;s character, general reputation, personal characteristics, or mode of living. Social Mints may compile investigative consumer reports about individuals and properties and provide them to businesses for background screening and similar purposes.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Personal Information Disclosure: United States or Overseas &ndash; In connection with its preparation and processing of investigative consumer reports Social Mints may transfer personal information about you to our authorized service providers and affiliates outside the United States and its territories. Such transfer will be conducted in accordance with all applicable laws and regulations.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">To obtain additional information about the privacy practices and policies of Social Mints Rental Property Solutions in connection with its preparation and processing of investigative consumer reports, please contact us using the details above.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">13. Annex</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">13.1 What is personal data?</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">&ldquo;<strong>Personal data</strong>&rdquo; is information about you (a &ldquo;<strong>data subject</strong>&rdquo;) the use of which is governed by applicable data protection laws. It will include any information from which you can be identified, directly or indirectly, in particular by reference to an identifier such as your name, an identification number, location data, an online identifier or other information about your identity. Most information collected about you on the Marketplace will constitute personal data.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">13.2 What is the legal basis for processing your personal data?</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">On some occasions, we process your personal data with your consent, for example, when you agree to receive our newsletter or to deal with your enquiries.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">On other occasions, we process your personal data when we need to do this in order to fulfil a contract with you, such as granting you access to our online services.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We also process your personal data when it is in our legitimate interests to do this and when these interests are not overridden by your data protection rights. For example, we may process your personal data in our legitimate interests to ensure that our Marketplace and services are provided efficiently and in an user-friendly and personalized manner taking into account user feedback, data and profiles, unless consent is required for any such processing under applicable law. We will process personal data to ensure the security of our business and the information of our users, and to ensure the proper and efficient administration of our business. You may contact us for further information.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Finally, we will process your personal data where we are required to do this by law. For example, where we have to fulfil anti-money laundering requirements or disclose information under a court order.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">13.3 Data transfers</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Personal data that we collect may be stored and processed in and transferred between any of the countries in which we operate in order to enable us to use the personal data in accordance with this Privacy Policy.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Personal data which you provide may be transferred to our group companies, commercial partners, suppliers or agents located outside your country as set out above. We will ensure adequate protection of personal data transferred outside of your country as required under applicable laws.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">13.4 How long does Social Mints keep personal data?</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Social Mints keeps your personal data for only as long as required to provide you with the necessary Marketplace content and services and to carry out the processing set out in this Privacy Notice, and in line with its obligation under applicable law. This means that we will generally not keep your personal data for longer than ten years following your last interaction with us, and the actual retention period will often be shorter. You may contact us for further information.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">13.5 Your rights</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Data subjects may ask us for a copy of their personal data, to correct it, erase it or to transfer it to other organizations at their request. Data subjects also have rights to object to some processing including profiling and, where we have asked for their consent to process the data subject&rsquo;s personal data, to withdraw this consent. In particular, data subjects have the right to object to direct marketing at any time. Where a data subject withdraws their consent, this will not affect the legitimacy of the processing conducted prior to your request. &nbsp;Where we process personal data because we have a legitimate interest in doing so (as explained above), the data subject has a right to object to this.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">These rights may be limited in some situations &ndash; for example, where we can demonstrate that we have a legal requirement to process your personal data.</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">We hope that we can satisfy queries you may have about the way we process your personal data. However, if you have unresolved concerns, you also have the right to complain to your local data protection authority.&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style="font-size:16px;line-height:107%;">14. Changes to this Statement</span></strong></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style="font-size:16px;line-height:107%;">Social Mints may from time to time and without prior notice revise this Privacy Policy. Any changes will be effective immediately when the revised Policy is posted on the Marketplace, unless stated otherwise. We will not, however, use your personal information in a manner materially different than what was stated in the Privacy Policy posted on the Marketplace at the time your personal information was collected unless we receive your consent.</span></p>



</div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>
    
    

    
    
    



